version: '3.1'

services:

  db:
    image: mcr.microsoft.com/mssql/server
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    container_name: mssql-data-sentry
    environment:
      SA_PASSWORD: "#Gfgrupo1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - dbdata-mssql:/var/opt/mssql

volumes:
  dbdata-mssql:


